### ISSUE TITLE
Packages not installed ERROR

### ISSUE THREAD

**Issue by danharsley** [UMEP-dev/UMEP#181]
Error when trying to install plugin?

**Comment by sunt05** [comment]
Sorry about this trouble, which may be caused by your system configuration that is preventing a dependency package to be installed.

We have fixed this in a development version, which hasn't yet been released.
I'll let you know once it's released; hopefully this week.
Then you just need to reinstall UMEP and relaunch QGIS.

If the issue persists, please let us know with more detailed information about your system.

**Comment by sunt05** [comment]
We have released a fix for supy to resolve this. Please try to reinstall UMEP and let us know here if things have been improved.

**Comment by biglimp** [comment]
Any new updates on this bug report? Was this issue resolved?

**Comment by biglimp** [comment]
I will close this as no response was send.
