### ISSUE TITLE
Error: Unable to allocate 5.15 GiB for an array with shape (411, 1681920) and data type float 64

### ISSUE THREAD

**Issue by cpk105** [UMEP-dev/UMEP#192]
Hi,

I encounter an error when I run the SUEWS model (Running the SUEWS model in UMEP) in this tutorial: https://umep-docs.readthedocs.io/projects/tutorial/en/latest/Tutorials/SuewsSpatial.html#suewsspatial

![image](https://user-images.githubusercontent.com/54835679/96964064-84d6b880-1555-11eb-8cea-dfd77fa8f141.png)

I'm using QGIS 3.14 on Windows. I have only 25 GB free space in my C drive. Is the shortage of space in C drive the cause of this error? Is there anything I can do to fix this error without making space in C drive?

Thank you.

Paul

**Comment by sunt05** [comment]
From the error message showing above, I cannot properly gather what is causing the issue.
But I guess it could be that your simulation domain/period is too large/long.

You may want to set up several batches of smaller domains and run them batch by batch; and see this would be helpful.

Otherwise, you need to post all your input data and then we can look into the exact cause for this.

**Comment by cpk105** [comment]
Thank you for your comments. I run the same thing in another computer with more free disk space and it worked.
