### ISSUE TITLE
Allow setting start and end times in shadow generator

### ISSUE THREAD

**Issue by elliots** [UMEP-dev/UMEP#229]
I'm trying to compare summer and winter, but there are less shadow images in winter (as presumably, the sun hasn't come up) but I think it could also be useful for generating images for certain parts of the day

**Comment by biglimp** [comment]
I will label this as an enhancement as it is not a blocking issue as such

**Comment by biglimp** [comment]
@vsoubry and @elliots , I am thinking on adding this feature. Any suggestions on how to do this?
My suggestion:

- Add a start date and time
- Add a end date and time
- Add a shadow casting interval
- Add a optional start time when shadows should be generated
- Add an optional end time when shadows no longer should be generated

**Comment by biglimp** [comment]
Update on this. The new version of QGIS 3.20 includes a new function where time and date can be more efficiently be included in a processing plugin. I will investigate further

**Comment by biglimp** [comment]
The datetime functionality has now been incorporated in the shadow casting algorithm in UMEP for processing (https://github.com/UMEP-dev/UMEP-processing/issues/10). There you can set the dates and times more specifically by e.g. doing a batch process or write a small script. Thus, I will close this issue here.
