### ISSUE TITLE
Error with ERA5/Copernicus Data Download Tool

### ISSUE THREAD

**Issue by kellyi-sfei** [UMEP-dev/UMEP#423]
**Describe the bug**
The tool appears to trigger a request the Copernicus data store (i.e., visible in my requests on their webpage), but not downloading/reformatting the data.

I'm getting the following error:
```
2022-06-08T17:08:28     CRITICAL    EXCEPTION IN ~/QGIS/QGIS3\profiles\default/python/plugins\UMEP\copernicus_data\WorkerDownload.py, 
             LINE 43 "sp.util.gen_forcing_era5(self.lat, self.lon, self.start_date, self.end_date, dir_save=Path(self.folderPath))" 
             ERROR MESSAGE: 'NoneType' object has no attribute 'write'
```
----
Note: I got to this error after editing the import lines in the following two files to correct NameError
copernicus_data.py, line 25
`from qgis.core import Qgis, QgsMessageLog`
and 
WorkerDownload.py
`import linecache`

**To Reproduce**
1. UMEP > Pre-processor > Meteorological Data > Download Data (Era5)
2. Enter Lat/Lon and Date range

**Desktop (please complete the following information):**
 - OS: Windows 10
 - QGIS Version 3.24.1
 - UMEP Version 3.19.3
 - SuPy Version 2022.4.7

**Comment by sunt05** [comment]
This is likely to be caused by a write access error.

Please check:
1. if the specified folder is valid location (e.g. not existing); or
2. if your python/QGIS has write access to the specified folder (e.g. see [here](https://stackoverflow.com/questions/2113427/determining-whether-a-directory-is-writeable)).

If not, please fix related issue; otherwise, please let us know here.

Meanwhile, we'll add something in the UMEP code to help determine the cause of such issues.

**Comment by biglimp** [comment]
@kellyi-sfei , was this solved? Can I close?

**Comment by kellyi-sfei** [comment]
Hi -

I'm sorry, I've lost tabs on this issue. I know I ended up downloading
directly from the Copernicus site instead of trying to sort out my problems
with downloading through the package. You can close.
----
Kelly Iknayan
Senior Scientist
Resilient Landscapes Program
San Francisco Estuary Institute
***@***.***>
*she/her*
