### ISSUE TITLE
Tree generator - 2m shift

### ISSUE THREAD

**Issue by sweco-se1a5m** [UMEP-dev/UMEP#670]
The raster created by the tree generator seems to be shifted approximetly 2m to -45 degrees.

in pink are the points used to create the trees and in green is a buffer representing the diameter of the tree.
(all files have the same coordinate system)

![Image](https://github.com/user-attachments/assets/87d30b58-4c33-4e53-a7be-6e1b7212c465)

**Comment by biglimp** [comment]
I cannot really replicate your error using the testdata provided. Can you send you point data and your surface grid that you use as a base.

![Image](https://github.com/user-attachments/assets/c5ec0570-b1eb-43fd-a99c-b840d1bd2b95)

**Comment by sweco-se1a5m** [comment]
ok you don't get the same problem, i will package that for you, thanks for the quick reply.

**Comment by sweco-se1a5m** [comment]
[Data_UMEP_Tree.zip](https://github.com/user-attachments/files/17777488/Data_UMEP_Tree.zip)
Here is the data, I included the CDSM output.

**Comment by biglimp** [comment]
I had a look. This is due to unfortunate founding transforming from vector to raster. As you have such small trees dia=3.5 and raster resolution of 1 meter, rounding to full numbers moves the position of the raster generated trees. I changed your diameter to 4 meters and got the results below. I suggest you do the same.

![Image](https://github.com/user-attachments/assets/15f0b6c6-a69e-41db-8e5d-4a152bc08d0a)

**Comment by sweco-se1a5m** [comment]
Ok, thank you for the help.
